theme = "minindieMod"
title = "Attt's Blog"
baseURL = "https://attt.github.io"
copyright = "2024 Attt's blog Powered by Hugo & minindie"

# Parameters
[params]
  subtitle = "Tech otakus save the world"
  dateFmt = "Monday, January 2, 2006"
  # tagPostOlderThanXDays = 555 # To display a message if the post is older than this number of days.
  # xslpath = "/rss.xsl" # If you want to theme your RSS feed. Optional.

[params.author]
  name = "Attt's blog" # required for h-card
  email = "atpexgo@gmail.com"
  avatar = "/images/favicon.png"
  bio = "A bio description<br />Html is accepted."

# [params.indieweb]
#   authorizationEndpoint = "https://indieauth.com/auth"
#   tokenEndpoint = "https://tokens.indieauth.com/token"
#   webmentionEndpoint = "https://webmention.io/your.domain.tld/webmention"
#   relmepgp = "/path/to//public/key.asc"
#   [[params.indieweb.relme]]
#       url = "https://"
#   [[params.indieweb.relme]]
#       url = "https://"

# Menus:
## Header
[menu]
  # [[menu.main]]
  #       identifier = "posts"
  #       name = "Posts"
  #       url = "/posts/"
  #       weight = 1

#   [[menu.main]]
#         identifier = "categories"
#         name = "Categories"
#         url = "/categories/"
#         weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

#   [[menu.main]]
#         identifier = "about"
#         name = "About"
#         url = "/about/"
#         weight = 4

## Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/Attt"
        weight = 1